<a href="https://colab.research.google.com/github/AndresUrregoAngel/Python/blob/master/ML/MatrixExploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from scipy import sparse

matrix = np.array([
    [2 , 0],
    [0 , 1],
    [3 , 0],
    [4 , 3],
    [0 , 5]
    
])

print(matrix)

[[2 0]
 [0 1]
 [3 0]
 [4 3]
 [0 5]]


In [10]:
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

# Explained result 
# ( which row the element starts , column from where the value come )   the values
#  (1, 1)   	1
#  (2, 0)	    3
#  (3, 0)   	4
#  (3, 1)	    3
#  (4, 1)	    5

  (0, 0)	2
  (1, 1)	1
  (2, 0)	3
  (3, 0)	4
  (3, 1)	3
  (4, 1)	5


In [50]:
# Picking elements from the array 

matrix = np.array([
    [4,5,6,7],
    [3,2,1,0],
    [4,0,6,7],
    [7,3,1,8]
])

# matrix[rows[location],columns[location] ]
print(matrix[3:4,-1:])

print(matrix.shape,' the shape') # the shape of the matrix 4x4
print(matrix.size ,'the number of elements within a matrix 16') # the number of elements within a matrix 16
print(matrix.ndim, 'number of dimension on the matrix 2') # number of dimension on the matrix 2

matrix_sparse = sparse.csr_matrix(matrix)
#print(matrix_sparse)


third_dim_matrix = np.zeros((1,1,3))
#3D array
new_m = np.array([   
    [
        [2,3],
        [1,1]
    ]
])

print(new_m[-1:,:1,-1:])
print(new_m,new_m.ndim)

[[8]]
(4, 4)  the shape
16 the number of elements within a matrix 16
2 number of dimension on the matrix 2
[[[3]]]
[[[2 3]
  [1 1]]] 3


Vectorized functions are able to apply an specific function across every element of a matrix

In [51]:
matrix = np.array([
    [3,4,2],
    [5,6,2]
])

#define my function
power_two = lambda i : pow(i,2)

# vectorize the function

vectorize_fnct = np.vectorize(power_two)

#Apply the function to the matrix
new_matrix = vectorize_fnct(matrix)

print(new_matrix)


[[ 9 16  4]
 [25 36  4]]
